apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: my-sample-app
          image: purushothamaws/jenkins-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
